name: Test - prefix integration

on:
  push:
    branches: [main, postpub]
  pull_request:
    branches: [main]

jobs:
  prefix-test:
    name: Run integration prefix test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run prefix integration test
        run: npx jest --runInBand src/__tests__/integration/prefix.test.ts -i --reporters=default
        env:
          CI: true
